apiVersion: v1
kind: Secret
metadata:
  name: order-service-dev-secret
  namespace: order-service
  labels:
    app: order-service-dev
    environment: dev
stringData:
  POSTGRES_DB: order
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  DB_USERNAME: postgres
  DB_PASSWORD: admin
  RABBITMQ_USERNAME: admin
  RABBITMQ_PASSWORD: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-homol-secret
  namespace: order-service
  labels:
    app: order-service-homol
    environment: homol
stringData:
  POSTGRES_DB: order
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: admin
  DB_USERNAME: postgres
  DB_PASSWORD: admin
  RABBITMQ_USERNAME: admin
  RABBITMQ_PASSWORD: admin
